import { expect, type Page } from '@playwright/test'

/* 스크린샷은 "어색하다"를 판단하지 못한다. 판단은 사람이 하고, 여기서는
 * 판단할 재료(아티팩트)를 남기는 데까지만 한다.
 *
 * 대신 "어색함"의 상당 부분은 어설션 가능한 증상으로 환원된다.
 * 콘솔 에러, 실패한 요청, 가로 스크롤, 깨진 이미지가 그것이다.
 * 이 모듈은 그 넷을 모은다. */

/* MSW 워커 스크립트(public/mockServiceWorker.js)가 설치된 msw보다 낮은 버전으로
 * 생성되어 매 페이지마다 경고를 찍는다. 목 환경에서만 나오고 제품과 무관하므로
 * 걸러낸다. `npx msw init public`으로 워커를 갱신하면 이 항목은 지워도 된다. */
const IGNORED_CONSOLE_PATTERNS = [
  /currently registered Service Worker has been generated by a different version of MSW/i,
  /* 리소스 로드 실패는 아래 requestfailed/response 훅이 URL과 함께 잡는다.
   * 콘솔로도 같은 사건이 한 번 더 오는데 이쪽 메시지에는 URL이 없어
   * 외부 이미지인지 우리 자원인지 구분할 수 없다. 중복이므로 버린다. */
  /^Failed to load resource:/i,
]

/* next/image 최적화 요청(_next/image)은 서버가 외부 호스트(i.ytimg.com 등)를
 * 직접 받아온다. 실행 환경에 외부 네트워크가 막혀 있으면 제품과 무관하게 실패하므로
 * 따로 모으고 단언하지 않는다. remotePatterns에는 이미 등록되어 있다. */
const EXTERNAL_IMAGE_REQUEST = /\/_next\/image\?/

/* 이미 파악된 결함. 단언으로 걸면 이 화면의 다른 신호까지 함께 묻히므로
 * 따로 모아 리포트에 드러내고, 고쳐지면 목록에서 지운다.
 *
 * /channels//videos — 채널 ID가 빈 문자열인 채로 경로가 조립된다.
 * 목 유저의 userChannelDetails가 null이라 재현되며, 채널 미연동 상태에서
 * 요청을 보내지 않고 건너뛰어야 할 자리로 보인다. 실서버였다면 그대로 나간다. */
const KNOWN_ISSUE_PATTERNS = [/\/channels\/\/videos/]

export interface PageProblems {
  consoleErrors: string[]
  failedRequests: string[]
  badResponses: string[]
  /* 참고용 — 단언 대상이 아니다 */
  externalImageFailures: string[]
  knownIssues: string[]
}

/* 페이지 수명 동안 발생한 문제를 모은다.
 * page.goto 이전에 붙여야 초기 로드의 에러를 놓치지 않는다. */
export function watchForProblems(page: Page): PageProblems {
  const problems: PageProblems = {
    consoleErrors: [],
    failedRequests: [],
    badResponses: [],
    externalImageFailures: [],
    knownIssues: [],
  }

  page.on('console', (msg) => {
    if (msg.type() !== 'error') return
    const text = msg.text()
    if (IGNORED_CONSOLE_PATTERNS.some((p) => p.test(text))) return
    problems.consoleErrors.push(text)
  })

  /* 렌더 중 던져진 예외. React 에러 바운더리에 잡히면 화면은 멀쩡해 보여도
   * 여기로는 올라온다. */
  page.on('pageerror', (error) => {
    problems.consoleErrors.push(`pageerror: ${error.message}`)
  })

  /* 네트워크 수준 실패(DNS, 연결 끊김 등). 4xx/5xx는 여기가 아니라 아래에서 잡힌다. */
  page.on('requestfailed', (request) => {
    const entry = `${request.method()} ${request.url()} — ${request.failure()?.errorText}`
    if (EXTERNAL_IMAGE_REQUEST.test(request.url())) {
      problems.externalImageFailures.push(entry)
      return
    }
    if (KNOWN_ISSUE_PATTERNS.some((p) => p.test(request.url()))) {
      problems.knownIssues.push(entry)
      return
    }
    /* 로그인 성공 시 window.location.href로 전체 새로고침이 걸리는데,
     * 그때 진행 중이던 문서 요청이 취소되며 ERR_ABORTED가 남는다.
     * 브라우저가 정상적으로 이전 탐색을 접은 것이지 실패가 아니다. */
    if (
      request.resourceType() === 'document' &&
      request.failure()?.errorText === 'net::ERR_ABORTED'
    ) {
      return
    }
    problems.failedRequests.push(entry)
  })

  page.on('response', (response) => {
    if (response.status() < 400) return
    const url = response.url()
    const entry = `${response.status()} ${response.request().method()} ${url}`
    if (EXTERNAL_IMAGE_REQUEST.test(url)) {
      problems.externalImageFailures.push(entry)
      return
    }
    if (KNOWN_ISSUE_PATTERNS.some((p) => p.test(url))) {
      problems.knownIssues.push(entry)
      return
    }
    problems.badResponses.push(entry)
  })

  return problems
}

export function expectNoProblems(problems: PageProblems) {
  expect(problems.consoleErrors, '콘솔 에러가 없어야 한다').toEqual([])
  expect(problems.failedRequests, '실패한 요청이 없어야 한다').toEqual([])
  expect(problems.badResponses, '4xx/5xx 응답이 없어야 한다').toEqual([])
}

/* 가로 스크롤은 레이아웃이 터졌다는 가장 흔한 신호다.
 * 스크린샷으로는 잘 안 보이지만(뷰포트만 찍히므로) 사용자는 바로 느낀다.
 *
 * 넘친 요소까지 함께 돌려준다. "몇 px 넘쳤다"만으로는 고칠 수 없고
 * 어느 요소가 밀어냈는지가 있어야 한다. */
export async function measureHorizontalOverflow(page: Page) {
  return page.evaluate(() => {
    const doc = document.documentElement
    const limit = doc.clientWidth
    const offenders: string[] = []

    document.querySelectorAll<HTMLElement>('*').forEach((el) => {
      const rect = el.getBoundingClientRect()
      if (rect.right > limit + 0.5 && rect.width > 0) {
        const cls =
          typeof el.className === 'string' ? el.className.slice(0, 90) : ''
        offenders.push(
          `${el.tagName.toLowerCase()} w=${Math.round(rect.width)} :: ${cls}`
        )
      }
    })

    return {
      scrollWidth: doc.scrollWidth,
      clientWidth: limit,
      overflowed: doc.scrollWidth > limit,
      offenders: offenders.slice(0, 5),
    }
  })
}

/* 이미지가 실패하면 자리는 차지하지만 그림이 없다.
 * naturalWidth가 0이면 로드되지 않은 것이다.
 *
 * 외부 호스트를 거치는 _next/image는 제외한다 — 위 EXTERNAL_IMAGE_REQUEST와
 * 같은 이유로, 실행 환경의 네트워크 상태에 따라 결과가 갈린다. */
export async function expectNoBrokenImages(page: Page) {
  const broken = await page.evaluate(() =>
    Array.from(document.images)
      .filter((img) => img.complete && img.naturalWidth === 0)
      .map((img) => img.currentSrc || img.src)
      .filter((src) => !src.includes('/_next/image?'))
  )

  expect(broken, '깨진 이미지가 없어야 한다').toEqual([])
}

/* 스크린샷은 baseline 비교(toHaveScreenshot)를 쓰지 않는다.
 * 폰트 렌더링이 OS마다 달라 Windows에서 만든 기준은 Linux에서 전부 실패한다.
 * 지금은 눈으로 보기 위한 아티팩트로만 남긴다. test-results/는 gitignore 대상이다. */
export async function captureFlowShot(page: Page, name: string) {
  await page.screenshot({
    path: `test-results/screenshots/${name}.png`,
    fullPage: true,
  })
}
